FROM node:20-alpine

WORKDIR /app

# Instala deps primeiro (melhor cache)
COPY package.json ./
RUN npm install

EXPOSE 5173

# Em dev o código entra via bind mount (docker-compose)
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]

