FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    PYTHONPATH=/app/src

WORKDIR /app

RUN pip install --no-cache-dir poetry

# Cache de dependências
COPY pyproject.toml ./
RUN poetry install --no-interaction --no-ansi --no-root

EXPOSE 8000

# Em dev o código entra via bind mount (docker-compose)
CMD ["poetry","run","uvicorn","app.main:app","--reload","--reload-dir","/app/src","--host","0.0.0.0","--port","8000"]

